"use client";
import { useQuery } from "@tanstack/react-query";
import { ArrowLeft,Printer } from "lucide-react";
import Link from "next/link";
import { apiClient } from "@/lib/api";
import { dateTime,rupiah } from "@/lib/utils";
import { Button } from "@/components/ui/button";
type Detail={sale:{number:string;created_at:string;subtotal:number;discount:number;tax:number;gateway_fee:number;grand_total:number;amount_paid:number;change_amount:number};items:{id:string;description:string;quantity:number;unit_price:number;subtotal:number}[];payments:{method:string;status:string}[];branch:{name:string;address:string;phone:string}};
export default function Receipt({params}:{params:Promise<{id:string}>}){const query=useQuery({queryKey:["receipt"],queryFn:async()=>{const {id}=await params;return apiClient<Detail>(`/sales/${id}`)}});const data=query.data?.data;if(!data)return <main className="grid min-h-screen place-items-center">Memuat bukti transaksi...</main>;return <main className="mx-auto min-h-screen max-w-[820px] bg-white p-6 sm:p-12"><div className="print-hidden mb-8 flex justify-between"><Link href="/dashboard/sales" className="flex items-center gap-2 text-sm font-semibold"><ArrowLeft className="size-4"/>Kembali</Link><Button onClick={()=>window.print()}><Printer className="size-4"/>Cetak</Button></div><section className="mx-auto max-w-[720px]"><header className="flex justify-between border-b-2 border-foreground pb-6"><div><h1 className="text-2xl font-black">{data.branch.name}</h1><p className="mt-2 max-w-sm text-sm text-muted-foreground">{data.branch.address}<br/>{data.branch.phone}</p></div><div className="text-right"><p className="text-xs font-bold uppercase tracking-wider text-muted-foreground">Invoice</p><p className="mt-1 text-lg font-black">{data.sale.number}</p><p className="mt-1 text-sm">{dateTime.format(new Date(data.sale.created_at))}</p></div></header><table className="my-7 w-full text-sm"><thead><tr className="border-b text-left"><th className="py-3">Item</th><th className="py-3 text-right">Qty</th><th className="py-3 text-right">Harga</th><th className="py-3 text-right">Jumlah</th></tr></thead><tbody>{data.items.map(item=><tr key={item.id} className="border-b"><td className="py-3 font-medium">{item.description}</td><td className="py-3 text-right">{item.quantity}</td><td className="py-3 text-right">{rupiah.format(item.unit_price)}</td><td className="py-3 text-right">{rupiah.format(item.subtotal)}</td></tr>)}</tbody></table><div className="ml-auto max-w-xs space-y-2 text-sm">{[["Subtotal",data.sale.subtotal],["Diskon",-data.sale.discount],["Pajak",data.sale.tax],["Biaya gateway",data.sale.gateway_fee]].map(([label,value])=><div className="flex justify-between" key={String(label)}><span>{label}</span><span>{rupiah.format(Number(value))}</span></div>)}<div className="flex justify-between border-t-2 border-foreground pt-3 text-lg font-black"><span>Total</span><span>{rupiah.format(data.sale.grand_total)}</span></div><div className="flex justify-between"><span>Dibayar</span><span>{rupiah.format(data.sale.amount_paid)}</span></div><div className="flex justify-between"><span>Kembali</span><span>{rupiah.format(data.sale.change_amount)}</span></div></div><footer className="mt-14 border-t pt-5 text-center text-xs text-muted-foreground"><p className="font-semibold text-foreground">Terima kasih telah mempercayakan motor Anda kepada kami.</p><p className="mt-1">Simpan bukti ini untuk riwayat servis dan klaim.</p></footer></section></main>}
