"use client";

import { useQuery } from "@tanstack/react-query";
import { BarChart3,BookOpen,Boxes,Building2,ChevronDown,ClipboardList,CreditCard,FileClock,Landmark,LayoutDashboard,LogOut,Menu,Package,ReceiptText,Settings,ShieldCheck,ShoppingCart,UserCog,Users,Wrench,X } from "lucide-react";
import Link from "next/link";
import { usePathname,useRouter } from "next/navigation";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { apiClient } from "@/lib/api";
import { cn } from "@/lib/utils";

const groups=[
 {id:"overview",label:"Utama",items:[{href:"/dashboard",label:"Ringkasan",icon:LayoutDashboard,permission:"dashboard.read"}]},
 {id:"operations",label:"Operasional",items:[{href:"/dashboard/work-orders",label:"Penerimaan & servis",icon:ClipboardList,permission:"work_order.read"},{href:"/dashboard/pos",label:"Kasir / POS",icon:ShoppingCart,permission:"sale.create"},{href:"/dashboard/sales",label:"Transaksi",icon:ReceiptText,permission:"sale.read"},{href:"/dashboard/payments",label:"Pembayaran",icon:CreditCard,permission:"payment.read"}]},
 {id:"masters",label:"Master data",items:[{href:"/dashboard/customers",label:"Pelanggan",icon:Users,permission:"customer.read"},{href:"/dashboard/vehicles",label:"Kendaraan",icon:Wrench,permission:"vehicle.read"},{href:"/dashboard/products",label:"Produk & jasa",icon:Package,permission:"product.read"},{href:"/dashboard/inventory",label:"Persediaan",icon:Boxes,permission:"inventory.read"}]},
 {id:"finance",label:"Keuangan",items:[{href:"/dashboard/accounts",label:"Chart of accounts",icon:Landmark,permission:"accounting.read"},{href:"/dashboard/journals",label:"Jurnal",icon:BookOpen,permission:"accounting.read"},{href:"/dashboard/reports",label:"Laporan",icon:BarChart3,permission:"report.read"}]},
 {id:"administration",label:"Administrasi",items:[{href:"/dashboard/users",label:"Pengguna",icon:UserCog,permission:"user.manage"},{href:"/dashboard/roles",label:"Role & permission",icon:ShieldCheck,permission:"role.manage"},{href:"/dashboard/branches",label:"Cabang",icon:Building2,permission:"branch.manage"},{href:"/dashboard/audit-logs",label:"Audit log",icon:FileClock,permission:"audit.read"},{href:"/dashboard/settings",label:"CMS & pengaturan",icon:Settings,permission:"settings.manage"}]},
];
type Me={name:string;email:string;permissions:string[];roles:string[]};

export function DashboardShell({children}:{children:React.ReactNode}){
 const pathname=usePathname();const router=useRouter();const [mobileOpen,setMobileOpen]=useState(false);const [expanded,setExpanded]=useState<Set<string>>(()=>new Set(groups.map(group=>group.id)));const me=useQuery({queryKey:["me"],queryFn:()=>apiClient<Me>("/auth/me")});const user=me.data?.data;const permissions=new Set(user?.permissions??[]);const owner=user?.roles.includes("owner");
 const visibleGroups=groups.map(group=>({...group,items:group.items.filter(item=>owner||permissions.has(item.permission))})).filter(group=>group.items.length>0);
 async function logout(){await fetch("/api/auth/logout",{method:"POST"});router.replace("/login");router.refresh()}
 function toggle(id:string){setExpanded(current=>{const next=new Set(current);if(next.has(id))next.delete(id);else next.add(id);return next})}
 const initials=(user?.name??"User").split(" ").slice(0,2).map(word=>word[0]).join("").toUpperCase();
 const sidebar=<><div className="flex h-20 items-center gap-3 px-6"><span className="grid size-10 place-items-center rounded-xl bg-primary text-white"><Wrench className="size-5"/></span><div><p className="font-bold leading-tight">BengkelOS</p><p className="text-xs text-muted-foreground">Operasional bengkel</p></div></div><nav className="flex-1 space-y-2 overflow-y-auto px-3 py-3">{visibleGroups.map(group=>{const isOpen=expanded.has(group.id);const hasActive=group.items.some(item=>item.href==="/dashboard"?pathname===item.href:pathname.startsWith(item.href));return <section key={group.id}><button type="button" aria-expanded={isOpen} onClick={()=>toggle(group.id)} className={cn("flex w-full items-center justify-between rounded-lg px-3 py-2 text-[11px] font-bold uppercase tracking-[.12em] text-muted-foreground hover:bg-muted",hasActive&&"text-foreground")}><span>{group.label}</span><ChevronDown className={cn("size-3.5 transition-transform",!isOpen&&"-rotate-90")}/></button>{isOpen&&<div className="mt-1 space-y-1">{group.items.map(item=>{const active=item.href==="/dashboard"?pathname===item.href:pathname.startsWith(item.href);return <Link key={item.href} href={item.href} onClick={()=>setMobileOpen(false)} className={cn("flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium text-muted-foreground transition hover:bg-muted hover:text-foreground",active&&"bg-primary/10 text-primary")}><item.icon className="size-4"/>{item.label}</Link>})}</div>}</section>})}</nav><div className="border-t p-3"><button onClick={logout} className="flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium text-muted-foreground hover:bg-muted"><LogOut className="size-4"/>Keluar</button></div></>;
 return <div className="min-h-screen bg-muted/40"><aside className="fixed inset-y-0 left-0 z-30 hidden w-64 flex-col border-r bg-white lg:flex">{sidebar}</aside>{mobileOpen&&<div className="fixed inset-0 z-40 lg:hidden"><button aria-label="Tutup menu" className="absolute inset-0 bg-black/30" onClick={()=>setMobileOpen(false)}/><aside className="relative flex h-full w-72 flex-col bg-white shadow-xl">{sidebar}<Button variant="ghost" size="icon" className="absolute right-3 top-5" onClick={()=>setMobileOpen(false)}><X className="size-5"/></Button></aside></div>}<header className="sticky top-0 z-20 flex h-16 items-center justify-between border-b bg-white/90 px-5 backdrop-blur lg:ml-64 lg:px-8"><Button variant="ghost" size="icon" className="lg:hidden" onClick={()=>setMobileOpen(true)}><Menu className="size-5"/></Button><div className="ml-auto flex items-center gap-3"><div className="hidden text-right sm:block"><p className="text-sm font-semibold">{user?.name??"Memuat..."}</p><p className="text-xs text-muted-foreground">{user?.email??""}</p></div><div className="grid size-9 place-items-center rounded-full bg-foreground text-xs font-bold text-white">{initials}</div></div></header><main className="p-5 lg:ml-64 lg:p-8">{children}</main></div>
}
