"use client";
import { flexRender,getCoreRowModel,useReactTable,type ColumnDef,type PaginationState,type SortingState,type VisibilityState } from "@tanstack/react-table";
import { ArrowDown,ArrowUp,ArrowUpDown,ChevronLeft,ChevronRight,Download,RefreshCw,Search,SlidersHorizontal } from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import { useMemo,useState } from "react";
import { apiClient } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

export type TableRow=Record<string,unknown>;
export type TableColumn={key:string;label:string;format?:(value:unknown,row:TableRow)=>React.ReactNode};
export function DataTable({endpoint,columns,defaultSort="created_at"}:{endpoint:string;columns:TableColumn[];defaultSort?:string}){
  const [pagination,setPagination]=useState<PaginationState>({pageIndex:0,pageSize:10});const [sorting,setSorting]=useState<SortingState>([{id:defaultSort,desc:true}]);const [search,setSearch]=useState("");const [visibility,setVisibility]=useState<VisibilityState>({});
  const queryString=new URLSearchParams({page:String(pagination.pageIndex+1),per_page:String(pagination.pageSize),search,sort:sorting[0]?.id??defaultSort,direction:sorting[0]?.desc===false?"asc":"desc"}).toString();
  const query=useQuery({queryKey:[endpoint,queryString],queryFn:()=>apiClient<TableRow[]>(`${endpoint}?${queryString}`),placeholderData:(previous)=>previous});
  const defs=useMemo<ColumnDef<TableRow>[]>(()=>columns.map(column=>({id:column.key,accessorFn:row=>row[column.key],header:({column:col})=><button className="flex items-center gap-1 font-semibold" onClick={()=>col.toggleSorting()}>{column.label}{col.getIsSorted()==="asc"?<ArrowUp className="size-3"/>:col.getIsSorted()==="desc"?<ArrowDown className="size-3"/>:<ArrowUpDown className="size-3 opacity-40"/>}</button>,cell:({row,getValue})=>column.format?column.format(getValue(),row.original):String(getValue()??"—")})),[columns]);
  const table=useReactTable({data:query.data?.data??[],columns:defs,pageCount:query.data?.meta?.last_page??-1,state:{pagination,sorting,columnVisibility:visibility},onPaginationChange:setPagination,onSortingChange:setSorting,onColumnVisibilityChange:setVisibility,manualPagination:true,manualSorting:true,getCoreRowModel:getCoreRowModel()});
  function exportCSV(){const visible=columns.filter(c=>visibility[c.key]!==false);const lines=[visible.map(c=>c.label),...(query.data?.data??[]).map(row=>visible.map(c=>String(row[c.key]??"")))];const csv=lines.map(line=>line.map(v=>`"${v.replaceAll('"','""')}"`).join(",")).join("\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));const anchor=document.createElement("a");anchor.href=url;anchor.download=`export-${new Date().toISOString().slice(0,10)}.csv`;anchor.click();URL.revokeObjectURL(url)}
  return <div className="rounded-2xl border bg-white shadow-sm"><div className="flex flex-col gap-3 border-b p-4 sm:flex-row sm:items-center"><div className="relative max-w-sm flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input value={search} onChange={e=>{setSearch(e.target.value);setPagination(p=>({...p,pageIndex:0}))}} placeholder="Cari data..." className="pl-9"/></div><div className="flex gap-2"><Button variant="outline" size="icon" title="Muat ulang" onClick={()=>query.refetch()}><RefreshCw className={`size-4 ${query.isFetching?"animate-spin":""}`}/></Button><details className="relative"><summary className="flex h-10 cursor-pointer list-none items-center gap-2 rounded-xl border px-3 text-sm font-semibold"><SlidersHorizontal className="size-4"/>Kolom</summary><div className="absolute right-0 z-10 mt-2 min-w-48 space-y-2 rounded-xl border bg-white p-3 shadow-xl">{table.getAllLeafColumns().map(col=><label key={col.id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={col.getIsVisible()} onChange={col.getToggleVisibilityHandler()}/>{columns.find(c=>c.key===col.id)?.label}</label>)}</div></details><Button variant="outline" onClick={exportCSV}><Download className="size-4"/>CSV</Button></div></div>
  <div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-muted/60 text-left"><tr>{table.getHeaderGroups().map(group=>group.headers.map(header=><th key={header.id} className="whitespace-nowrap px-5 py-3">{header.isPlaceholder?null:flexRender(header.column.columnDef.header,header.getContext())}</th>))}</tr></thead><tbody>{query.isLoading?Array.from({length:5}).map((_,i)=><tr key={i}><td colSpan={columns.length} className="px-5 py-4"><div className="h-5 animate-pulse rounded bg-muted"/></td></tr>):query.error?<tr><td colSpan={columns.length} className="p-8 text-center text-destructive">{query.error.message}</td></tr>:table.getRowModel().rows.length===0?<tr><td colSpan={columns.length} className="p-10 text-center text-muted-foreground">Belum ada data.</td></tr>:table.getRowModel().rows.map(row=><tr key={row.id} className="border-t hover:bg-muted/30">{row.getVisibleCells().map(cell=><td key={cell.id} className="whitespace-nowrap px-5 py-3.5">{flexRender(cell.column.columnDef.cell,cell.getContext())}</td>)}</tr>)}</tbody></table></div>
  <div className="flex flex-col gap-3 border-t p-4 text-sm sm:flex-row sm:items-center sm:justify-between"><p className="text-muted-foreground">Total {query.data?.meta?.total??0} data</p><div className="flex items-center gap-2"><select className="h-9 rounded-lg border bg-white px-2" value={pagination.pageSize} onChange={e=>table.setPageSize(Number(e.target.value))}>{[10,25,50,100].map(size=><option key={size} value={size}>{size}/halaman</option>)}</select><span className="px-2">Halaman {pagination.pageIndex+1} / {Math.max(1,query.data?.meta?.last_page??1)}</span><Button variant="outline" size="icon" disabled={!table.getCanPreviousPage()} onClick={()=>table.previousPage()}><ChevronLeft className="size-4"/></Button><Button variant="outline" size="icon" disabled={!table.getCanNextPage()} onClick={()=>table.nextPage()}><ChevronRight className="size-4"/></Button></div></div></div>
}
