"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
import { ArrowLeft,CheckCircle2,PackagePlus,ShoppingCart,Trash2,Wrench } from "lucide-react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect,useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card";
import { Dialog,DialogContent,DialogDescription,DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { apiClient } from "@/lib/api";
import { dateTime,rupiah } from "@/lib/utils";

type Detail={work_order:{id:string;number:string;status:string;complaint:string;diagnosis:string;mechanic_id?:string;odometer:number;created_at:string;started_at?:string;completed_at?:string};customer:{name:string;phone:string};vehicle:{identifier:string;plate_number:string;brand:string;model:string;year:number;color:string};mechanic?:{id:string;name:string};items:Array<{id:string;product_id:string;product_sku:string;description:string;type:string;quantity:number;unit_price:number;subtotal:number;stock_deducted:boolean}>;subtotal:number;sale?:{id:string;status:string};payment?:{id:string;method:string;status:string}};
type Mechanic={id:string;name:string};type Product={id:string;sku:string;name:string;type:string;selling_price:number};
const itemSchema=z.object({product_id:z.string().uuid("Pilih produk"),quantity:z.coerce.number().positive(),discount:z.coerce.number().min(0)});type ItemForm=z.infer<typeof itemSchema>;
const labels:Record<string,string>={inspection:"Pemeriksaan",approval:"Menunggu persetujuan",in_progress:"Sedang dikerjakan",completed:"Selesai",invoiced:"Sudah ditagihkan",cancelled:"Dibatalkan"};
const nextStatus:Record<string,{status:string;label:string}>={inspection:{status:"approval",label:"Selesaikan pemeriksaan"},approval:{status:"in_progress",label:"Mulai pengerjaan"},in_progress:{status:"completed",label:"Selesaikan pekerjaan"}};

export default function WorkOrderPage(){
 const {id}=useParams<{id:string}>();const client=useQueryClient();const [itemOpen,setItemOpen]=useState(false);const detail=useQuery({queryKey:["work-order",id],queryFn:()=>apiClient<Detail>(`/work-orders/${id}`)});const mechanics=useQuery({queryKey:["mechanics"],queryFn:()=>apiClient<Mechanic[]>("/work-orders/options/mechanics")});const products=useQuery({queryKey:["work-order-products"],queryFn:()=>apiClient<Product[]>("/products?per_page=100&sort=name&direction=asc")});const data=detail.data?.data;
 const [diagnosis,setDiagnosis]=useState("");const [mechanicID,setMechanicID]=useState("");const {register,handleSubmit,reset,formState:{errors}}=useForm<ItemForm>({resolver:zodResolver(itemSchema),defaultValues:{product_id:"",quantity:1,discount:0}});
 useEffect(()=>{if(data){setDiagnosis(data.work_order.diagnosis??"");setMechanicID(data.work_order.mechanic_id??"")}},[data]);
 const update=useMutation({mutationFn:(status:string)=>apiClient(`/work-orders/${id}`,{method:"PATCH",body:JSON.stringify({status,diagnosis,mechanic_id:mechanicID||null})}),onSuccess:()=>client.invalidateQueries({queryKey:["work-order",id]})});
 const addItem=useMutation({mutationFn:(values:ItemForm)=>apiClient(`/work-orders/${id}/items`,{method:"POST",body:JSON.stringify(values)}),onSuccess:()=>{client.invalidateQueries({queryKey:["work-order",id]});client.invalidateQueries({queryKey:["/inventory"]});setItemOpen(false);reset()}});
 async function removeItem(itemID:string){if(!window.confirm("Hapus item dan kembalikan stoknya?"))return;await apiClient(`/work-orders/${id}/items/${itemID}`,{method:"DELETE"});client.invalidateQueries({queryKey:["work-order",id]});client.invalidateQueries({queryKey:["/inventory"]})}
 if(detail.isLoading)return <div className="p-10 text-center">Memuat work order...</div>;if(!data)return <div className="rounded-xl border bg-white p-8 text-red-700">{detail.error?.message??"Work order tidak ditemukan"}</div>;
 const locked=["completed","invoiced","cancelled"].includes(data.work_order.status);const next=nextStatus[data.work_order.status];
 return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><Link href="/dashboard/work-orders" className="mb-3 inline-flex items-center gap-2 text-sm font-semibold text-muted-foreground"><ArrowLeft className="size-4"/>Work order</Link><div className="flex items-center gap-3"><h1 className="text-3xl font-bold">{data.work_order.number}</h1><Badge>{labels[data.work_order.status]}</Badge></div><p className="mt-2 text-muted-foreground">Diterima {dateTime.format(new Date(data.work_order.created_at))}</p></div>{data.work_order.status==="completed"&&<Link href={`/dashboard/pos?work_order_id=${id}`} className="inline-flex h-11 items-center gap-2 rounded-xl bg-primary px-5 text-sm font-semibold text-white"><ShoppingCart className="size-4"/>Bayar work order</Link>}{data.work_order.status==="invoiced"&&data.sale&&<Link href={`/print/receipt/${data.sale.id}`} className="inline-flex h-11 items-center gap-2 rounded-xl bg-primary px-5 text-sm font-semibold text-white"><ShoppingCart className="size-4"/>{data.payment?.status==="pending"?"Lanjutkan pembayaran":"Lihat transaksi"}</Link>}</div>
 <div className="grid gap-5 lg:grid-cols-3"><Card><CardHeader><CardTitle>Pelanggan & motor</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><div><p className="text-muted-foreground">Pelanggan</p><p className="font-semibold">{data.customer.name} · {data.customer.phone||"—"}</p></div><div><p className="text-muted-foreground">Motor</p><p className="font-semibold">{data.vehicle.identifier}</p><p>{data.vehicle.brand} {data.vehicle.model} {data.vehicle.year||""} · {data.vehicle.color}</p></div><div><p className="text-muted-foreground">Odometer</p><p className="font-semibold">{data.work_order.odometer.toLocaleString("id-ID")} km</p></div></CardContent></Card><Card className="lg:col-span-2"><CardHeader><CardTitle className="flex items-center gap-2"><Wrench className="size-5"/>Pemeriksaan montir</CardTitle></CardHeader><CardContent className="space-y-4"><div className="rounded-xl bg-muted p-4"><p className="text-xs font-semibold uppercase text-muted-foreground">Keluhan</p><p className="mt-1">{data.work_order.complaint}</p></div><label className="block text-sm font-medium">Montir<select disabled={locked} className="mt-2 h-10 w-full rounded-xl border bg-white px-3" value={mechanicID} onChange={event=>setMechanicID(event.target.value)}><option value="">Pilih montir</option>{mechanics.data?.data?.map(mechanic=><option key={mechanic.id} value={mechanic.id}>{mechanic.name}</option>)}</select></label><label className="block text-sm font-medium">Diagnosis<textarea disabled={locked} className="mt-2 min-h-28 w-full rounded-xl border p-3 text-sm disabled:bg-muted" value={diagnosis} onChange={event=>setDiagnosis(event.target.value)}/></label><div className="flex flex-wrap gap-2">{!locked&&<Button variant="outline" onClick={()=>update.mutate(data.work_order.status)} disabled={update.isPending}>Simpan pemeriksaan</Button>}{next&&<Button onClick={()=>update.mutate(next.status)} disabled={update.isPending}><CheckCircle2 className="size-4"/>{next.label}</Button>}{!locked&&<Button variant="destructive" onClick={()=>update.mutate("cancelled")}>Batalkan</Button>}</div>{update.error&&<p className="text-sm text-red-600">{update.error.message}</p>}</CardContent></Card></div>
 <Card><CardHeader><div className="flex items-center justify-between"><CardTitle>Barang dan jasa terpakai</CardTitle>{!locked&&<Button onClick={()=>setItemOpen(true)}><PackagePlus className="size-4"/>Tambah item</Button>}</div></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="py-3">SKU</th><th>Barang/jasa</th><th>Tipe</th><th className="text-right">Qty</th><th className="text-right">Harga</th><th className="text-right">Subtotal</th><th/></tr></thead><tbody>{data.items.map(item=><tr key={item.id} className="border-b"><td className="py-3 font-mono">{item.product_sku}</td><td>{item.description}</td><td>{item.type}</td><td className="text-right">{item.quantity}</td><td className="text-right">{rupiah.format(item.unit_price)}</td><td className="text-right font-semibold">{rupiah.format(item.subtotal)}</td><td className="text-right">{!locked&&<Button variant="ghost" size="icon" onClick={()=>removeItem(item.id)}><Trash2 className="size-4 text-red-600"/></Button>}</td></tr>)}{data.items.length===0&&<tr><td colSpan={7} className="py-10 text-center text-muted-foreground">Belum ada barang atau jasa.</td></tr>}</tbody><tfoot><tr><td colSpan={5} className="pt-4 text-right font-bold">Estimasi total</td><td className="pt-4 text-right text-lg font-black">{rupiah.format(data.subtotal)}</td><td/></tr></tfoot></table></div></CardContent></Card>
 <Dialog open={itemOpen} onOpenChange={setItemOpen}><DialogContent><DialogTitle>Catat barang atau jasa</DialogTitle><DialogDescription>Stok barang langsung berkurang saat item disimpan. Jasa tidak memengaruhi stok.</DialogDescription><form className="mt-6 space-y-4" onSubmit={handleSubmit(values=>addItem.mutate(values))}><label className="block text-sm font-medium">Produk<select className="mt-2 h-10 w-full rounded-xl border bg-white px-3" {...register("product_id")}><option value="">Pilih barang/jasa</option>{products.data?.data?.map(product=><option key={product.id} value={product.id}>{product.sku} · {product.name} · {rupiah.format(product.selling_price)}</option>)}</select>{errors.product_id&&<span className="text-xs text-red-600">{errors.product_id.message}</span>}</label><div className="grid grid-cols-2 gap-4"><label className="text-sm font-medium">Jumlah<Input className="mt-2" type="number" step=".001" {...register("quantity",{valueAsNumber:true})}/></label><label className="text-sm font-medium">Diskon<Input className="mt-2" type="number" {...register("discount",{valueAsNumber:true})}/></label></div>{addItem.error&&<p className="text-sm text-red-600">{addItem.error.message}</p>}<div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={()=>setItemOpen(false)}>Batal</Button><Button disabled={addItem.isPending}>Tambahkan</Button></div></form></DialogContent></Dialog></div>
}
