import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, CheckCircle2, Clock3, Gauge, MapPin, ShieldCheck, Wrench } from "lucide-react";
import { serverApi } from "@/lib/server-api";

type HomeContent={hero?:{eyebrow?:string;title?:string;description?:string;primary_cta?:string};features?:{title:string;description:string}[]};
type CMSPage={meta_title:string;meta_description:string;content:HomeContent};
const fallback:HomeContent={hero:{eyebrow:"Servis motor tanpa drama",title:"Motor sehat, perjalanan tenang.",description:"Perawatan transparan, suku cadang terjamin, dan riwayat servis yang selalu tercatat.",primary_cta:"Buat Janji Servis"},features:[{title:"Pemeriksaan menyeluruh",description:"Diagnosis jelas sebelum pengerjaan dimulai."},{title:"Harga transparan",description:"Setiap barang dan jasa tercatat rinci."},{title:"Mekanik berpengalaman",description:"Ditangani tim yang paham motor Anda."}]};

export async function generateMetadata():Promise<Metadata>{const page=await serverApi<CMSPage>("/public/pages/home");return{title:page?.data?.meta_title??"Servis Motor Terpercaya",description:page?.data?.meta_description??fallback.hero?.description,alternates:{canonical:"/"}}}

export default async function LandingPage(){
  const page=await serverApi<CMSPage>("/public/pages/home");const content=page?.data?.content??fallback;
  return <main className="overflow-hidden">
    <nav className="absolute inset-x-0 top-0 z-20"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-6"><Link href="/" className="flex items-center gap-3 font-bold"><span className="grid size-10 place-items-center rounded-xl bg-primary text-white"><Wrench className="size-5"/></span><span>Maju Motor</span></Link><div className="hidden items-center gap-8 text-sm font-medium md:flex"><a href="#layanan">Layanan</a><a href="#cara-kerja">Cara kerja</a><a href="#kontak">Kontak</a></div><Link href="/login" className="rounded-xl border border-foreground/15 bg-white/70 px-4 py-2 text-sm font-semibold backdrop-blur">Masuk staf</Link></div></nav>
    <section className="dot-grid relative min-h-[820px] pt-36"><div className="absolute -right-40 top-10 size-[520px] rounded-full bg-orange-200/60 blur-3xl"/><div className="mx-auto grid max-w-7xl items-center gap-14 px-6 py-20 lg:grid-cols-[1.05fr_.95fr]"><div className="relative"><p className="mb-6 inline-flex items-center gap-2 rounded-full border bg-white px-4 py-2 text-sm font-semibold text-primary shadow-sm"><Gauge className="size-4"/>{content.hero?.eyebrow}</p><h1 className="max-w-3xl font-display text-5xl font-extrabold leading-[1.05] tracking-[-.045em] md:text-7xl">{content.hero?.title}</h1><p className="mt-7 max-w-xl text-lg leading-8 text-muted-foreground">{content.hero?.description}</p><div className="mt-9 flex flex-wrap gap-3"><a href="https://wa.me/6281234567890" className="inline-flex h-12 items-center gap-2 rounded-xl bg-primary px-6 font-semibold text-white shadow-lg shadow-primary/20">{content.hero?.primary_cta}<ArrowRight className="size-4"/></a><a href="#layanan" className="inline-flex h-12 items-center rounded-xl border bg-white px-6 font-semibold">Lihat layanan</a></div><div className="mt-10 flex flex-wrap gap-x-8 gap-y-3 text-sm text-muted-foreground"><span className="flex items-center gap-2"><CheckCircle2 className="size-4 text-emerald-600"/>Estimasi transparan</span><span className="flex items-center gap-2"><CheckCircle2 className="size-4 text-emerald-600"/>Riwayat tercatat</span></div></div>
      <div className="relative mx-auto w-full max-w-xl"><div className="absolute -inset-5 rotate-3 rounded-[2rem] bg-foreground"/><div className="relative overflow-hidden rounded-[2rem] border bg-white p-7 shadow-2xl"><div className="flex items-center justify-between border-b pb-5"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-muted-foreground">Status servis</p><p className="mt-1 text-xl font-bold">B 1234 XYZ</p></div><span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-bold text-emerald-700">Sedang dikerjakan</span></div><div className="space-y-5 py-7">{[["08:12","Motor diterima","Selesai"],["08:35","Pemeriksaan mekanik","Selesai"],["09:10","Penggantian oli & tune up","Berlangsung"],["—","Quality control","Menunggu"]].map(([time,title,status],i)=><div className="flex gap-4" key={title}><div className={`mt-1 size-3 shrink-0 rounded-full ${i<2?"bg-emerald-500":i===2?"bg-primary ring-4 ring-primary/15":"bg-muted"}`}/><div className="flex-1"><div className="flex justify-between gap-4"><p className="font-semibold">{title}</p><p className="text-sm text-muted-foreground">{time}</p></div><p className="text-sm text-muted-foreground">{status}</p></div></div>)}</div><div className="rounded-2xl bg-muted p-5"><div className="flex justify-between text-sm"><span>Estimasi selesai</span><strong>Hari ini, 10:30</strong></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white"><div className="h-full w-2/3 rounded-full bg-primary"/></div></div></div></div>
    </div></section>
    <section id="layanan" className="bg-foreground py-24 text-white"><div className="mx-auto max-w-7xl px-6"><p className="text-sm font-bold uppercase tracking-[.2em] text-orange-400">Kenapa kami</p><h2 className="mt-4 max-w-2xl font-display text-4xl font-bold tracking-tight md:text-5xl">Pengerjaan rapi. Informasi jelas.</h2><div className="mt-12 grid gap-5 md:grid-cols-3">{(content.features??fallback.features)!.map((item,i)=>{const Icon=[ShieldCheck,Gauge,Wrench][i%3];return <article key={item.title} className="rounded-2xl border border-white/10 bg-white/[.04] p-7"><Icon className="size-8 text-orange-400"/><h3 className="mt-8 text-xl font-bold">{item.title}</h3><p className="mt-3 leading-7 text-white/60">{item.description}</p></article>})}</div></div></section>
    <section id="cara-kerja" className="py-24"><div className="mx-auto max-w-7xl px-6"><div className="grid gap-12 lg:grid-cols-2"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-primary">Proses sederhana</p><h2 className="mt-4 font-display text-4xl font-bold tracking-tight">Dari datang hingga pulang, semuanya tercatat.</h2></div><div className="grid gap-4">{[["01","Datang & registrasi","Kasir mencatat pelanggan dan identitas motor."],["02","Inspeksi & persetujuan","Mekanik memeriksa, lalu estimasi dikonfirmasi."],["03","Pengerjaan & pembayaran","Barang dan jasa tercatat sampai bukti transaksi dicetak."]].map(([num,title,desc])=><div key={num} className="flex gap-5 rounded-2xl border bg-white p-6"><span className="text-2xl font-black text-primary">{num}</span><div><h3 className="font-bold">{title}</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">{desc}</p></div></div>)}</div></div></div></section>
    <footer id="kontak" className="border-t bg-white py-12"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-6 px-6 md:flex-row"><div><p className="font-bold">Bengkel Maju Motor</p><p className="mt-2 flex items-center gap-2 text-sm text-muted-foreground"><MapPin className="size-4"/>Jl. Raya Otomotif No. 88, Jakarta</p></div><p className="flex items-center gap-2 text-sm text-muted-foreground"><Clock3 className="size-4"/>Senin–Sabtu, 08.00–17.00</p></div></footer>
  </main>
}
