"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { useQuery } from "@tanstack/react-query";
import { Minus,Plus,Printer,Search,ShoppingCart,Trash2,Wrench } from "lucide-react";
import { useRouter,useSearchParams } from "next/navigation";
import Script from "next/script";
import { Suspense,useState } from "react";
import { useFieldArray,useForm } from "react-hook-form";
import { z } from "zod";
import { apiClient } from "@/lib/api";
import { rupiah } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";

type Product={id:string;sku:string;name:string;type:string;selling_price:number};
type Customer={id:string;code:string;name:string;phone:string};
type WorkOrderDetail={work_order:{id:string;number:string;status:string};customer:{id:string;name:string};vehicle:{identifier:string;brand:string;model:string};items:Array<{id:string;product_id:string;description:string;type:string;quantity:number;unit_price:number;discount:number;subtotal:number}>;subtotal:number};
declare global { interface Window { snap?: { pay:(token:string,callbacks:{onSuccess:()=>void;onPending:()=>void;onError:()=>void;onClose:()=>void})=>void } } }
const schema=z.object({work_order_id:z.string().optional(),customer_id:z.string().optional(),payment_method:z.enum(["cash","midtrans"]),fee_bearer:z.enum(["merchant","customer","split"]),amount_paid:z.coerce.number().min(0),discount:z.coerce.number().min(0),items:z.array(z.object({product_id:z.string().uuid(),quantity:z.coerce.number().positive(),discount:z.coerce.number().min(0)}))}).superRefine((value,ctx)=>{if(!value.work_order_id&&value.items.length===0)ctx.addIssue({code:"custom",path:["items"],message:"Pilih minimal satu item"})});
type Form=z.infer<typeof schema>;

export default function POSPage(){return <Suspense fallback={<div className="p-10 text-center">Memuat kasir...</div>}><POSContent/></Suspense>}

function POSContent(){
 const router=useRouter();const params=useSearchParams();const workOrderID=params.get("work_order_id")??"";const [search,setSearch]=useState("");
 const products=useQuery({queryKey:["pos-products"],queryFn:()=>apiClient<Product[]>("/products?per_page=100&sort=name&direction=asc")});
 const customers=useQuery({queryKey:["pos-customers"],queryFn:()=>apiClient<Customer[]>("/customers?per_page=100&sort=name&direction=asc")});
 const workOrder=useQuery({queryKey:["pos-work-order",workOrderID],queryFn:()=>apiClient<WorkOrderDetail>(`/work-orders/${workOrderID}`),enabled:Boolean(workOrderID)});
 const {register,control,watch,setValue,handleSubmit,formState:{errors,isSubmitting},setError}=useForm<Form>({resolver:zodResolver(schema),defaultValues:{work_order_id:workOrderID||undefined,payment_method:"cash",fee_bearer:"customer",amount_paid:0,discount:0,items:[]}});
 const {fields,append,remove}=useFieldArray({control,name:"items"});const values=watch();const lines=fields.map((field,index)=>{const product=products.data?.data?.find(row=>row.id===field.product_id);return{...field,product,quantity:Number(values.items?.[index]?.quantity??1)}});const service=workOrder.data?.data;const subtotal=service?.subtotal??lines.reduce((sum,line)=>sum+(line.product?.selling_price??0)*line.quantity,0);const total=Math.max(0,subtotal-Number(values.discount??0));
 function add(product:Product){const index=fields.findIndex(field=>field.product_id===product.id);if(index>=0){setValue(`items.${index}.quantity`,Number(values.items[index].quantity)+1);return}append({product_id:product.id,quantity:1,discount:0})}
 async function submit(form:Form){try{const payload=await apiClient<{sale:{id:string};payment:{id:string;method:string;status:string}}>("/sales/checkout",{method:"POST",body:JSON.stringify({...form,work_order_id:workOrderID||undefined,customer_id:workOrderID?undefined:form.customer_id||undefined,items:workOrderID?undefined:form.items,tax:0,notes:workOrderID?`Checkout work order ${service?.work_order.number}`:"Transaksi POS"})});const result=payload.data;if(!result)return;const receiptURL=`/print/receipt/${result.sale.id}`;if(result.payment.method==="midtrans"){const finish=async()=>{try{await apiClient(`/payments/${result.payment.id}/midtrans/sync`,{method:"POST"})}finally{router.push(receiptURL)}};const snap=await apiClient<{token:string}>(`/payments/${result.payment.id}/midtrans/snap`,{method:"POST"});if(!snap.data?.token||!window.snap){router.push(receiptURL);return}window.snap.pay(snap.data.token,{onSuccess:()=>{void finish()},onPending:()=>{void finish()},onError:()=>router.push(receiptURL),onClose:()=>router.push(receiptURL)});return}router.push(receiptURL)}catch(error){setError("root",{message:error instanceof Error?error.message:"Checkout gagal"})}}
 const filtered=products.data?.data?.filter(product=>`${product.sku} ${product.name}`.toLowerCase().includes(search.toLowerCase()))??[];
 return <div className="space-y-6"><Script src={process.env.NEXT_PUBLIC_MIDTRANS_SNAP_URL??"https://app.sandbox.midtrans.com/snap/snap.js"} data-client-key={process.env.NEXT_PUBLIC_MIDTRANS_CLIENT_KEY}/><div><h1 className="text-3xl font-bold tracking-tight">{workOrderID?"Pembayaran servis":"Kasir / POS"}</h1><p className="mt-2 text-muted-foreground">{workOrderID?"Tagihkan seluruh barang dan jasa dari work order selesai.":"Penjualan barang atau jasa langsung tanpa work order."}</p></div>{workOrderID&&workOrder.isError&&<p className="rounded-xl bg-red-50 p-4 text-red-700">{workOrder.error.message}</p>}<form onSubmit={handleSubmit(submit)} className="grid gap-5 xl:grid-cols-[1.15fr_.85fr]"><input type="hidden" {...register("work_order_id")}/>
 <Card><CardHeader><CardTitle className="flex items-center gap-2">{workOrderID?<><Wrench className="size-5"/>Item work order</>:<>Pilih barang atau jasa</>}</CardTitle></CardHeader><CardContent>{service?<><div className="mb-5 rounded-xl bg-muted p-4 text-sm"><p className="font-bold">{service.work_order.number} · {service.vehicle.identifier}</p><p className="mt-1 text-muted-foreground">{service.customer.name} · {service.vehicle.brand} {service.vehicle.model}</p></div><div className="space-y-2">{service.items.map(item=><div key={item.id} className="flex items-center justify-between rounded-xl border p-4"><div><p className="font-semibold">{item.description}</p><p className="text-xs text-muted-foreground">{item.type} · {item.quantity} × {rupiah.format(item.unit_price)}</p></div><strong>{rupiah.format(item.subtotal)}</strong></div>)}</div></>:<><div className="relative mb-4"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Cari SKU atau nama produk..." className="pl-9"/></div><div className="grid gap-3 sm:grid-cols-2">{filtered.map(product=><button type="button" key={product.id} onClick={()=>add(product)} className="rounded-xl border p-4 text-left transition hover:border-primary hover:bg-primary/5"><span className="text-xs font-semibold text-muted-foreground">{product.sku} · {product.type}</span><p className="mt-1 font-semibold">{product.name}</p><p className="mt-3 text-sm font-bold text-primary">{rupiah.format(product.selling_price)}</p></button>)}</div></>}</CardContent></Card>
 <Card className="h-fit xl:sticky xl:top-24"><CardHeader><CardTitle className="flex items-center gap-2"><ShoppingCart className="size-5"/>Tagihan</CardTitle></CardHeader><CardContent>{!workOrderID&&<><label className="mb-4 block text-sm">Pelanggan (opsional)<select className="mt-2 h-10 w-full rounded-xl border bg-white px-3" {...register("customer_id")}><option value="">Pelanggan umum</option>{customers.data?.data?.map(customer=><option key={customer.id} value={customer.id}>{customer.code} · {customer.name}</option>)}</select></label><div className="space-y-3">{lines.length===0&&<p className="rounded-xl bg-muted p-5 text-center text-sm text-muted-foreground">Belum ada item.</p>}{lines.map((line,index)=><div key={line.id} className="rounded-xl border p-3"><div className="flex justify-between gap-3"><div><p className="font-semibold">{line.product?.name}</p><p className="text-xs text-muted-foreground">{rupiah.format(line.product?.selling_price??0)}</p></div><Button type="button" variant="ghost" size="icon" onClick={()=>remove(index)}><Trash2 className="size-4 text-destructive"/></Button></div><div className="mt-3 flex items-center gap-2"><Button type="button" variant="outline" size="icon" onClick={()=>setValue(`items.${index}.quantity`,Math.max(1,line.quantity-1))}><Minus className="size-3"/></Button><Input className="w-16 text-center" type="number" step=".001" {...register(`items.${index}.quantity`,{valueAsNumber:true})}/><Button type="button" variant="outline" size="icon" onClick={()=>setValue(`items.${index}.quantity`,line.quantity+1)}><Plus className="size-3"/></Button><strong className="ml-auto">{rupiah.format((line.product?.selling_price??0)*line.quantity)}</strong></div></div>)}</div></>}
 <div className="my-5 space-y-3 border-y py-5"><label className="flex items-center justify-between gap-4 text-sm"><span>Diskon transaksi</span><Input className="w-36 text-right" type="number" {...register("discount",{valueAsNumber:true})}/></label><div className="flex justify-between text-sm"><span>Subtotal</span><span>{rupiah.format(subtotal)}</span></div><div className="flex justify-between text-lg font-bold"><span>Total</span><span>{rupiah.format(total)}</span></div></div><div className="grid grid-cols-2 gap-3"><label className="text-sm">Metode<select className="mt-2 h-10 w-full rounded-xl border bg-white px-3" {...register("payment_method")}><option value="cash">Tunai</option><option value="midtrans">Midtrans</option></select></label><label className="text-sm">Biaya gateway<select className="mt-2 h-10 w-full rounded-xl border bg-white px-3" {...register("fee_bearer")}><option value="customer">Pelanggan</option><option value="merchant">Bengkel</option><option value="split">Dibagi</option></select></label></div>{values.payment_method==="cash"&&<label className="mt-4 block text-sm">Uang diterima<Input className="mt-2" type="number" {...register("amount_paid",{valueAsNumber:true})}/></label>}{(errors.items||errors.root)&&<p className="mt-3 text-sm text-destructive">{errors.items?.message??errors.root?.message}</p>}<Button size="lg" className="mt-5 w-full" disabled={isSubmitting||Boolean(workOrderID&&!service)||(!workOrderID&&fields.length===0)}><Printer className="size-4"/>{isSubmitting?"Memproses...":"Bayar & cetak"}</Button></CardContent></Card></form></div>
}
