"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { useMutation,useQueryClient } from "@tanstack/react-query";
import { Pencil,Plus,Trash2 } from "lucide-react";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { DataTable,type TableRow } from "@/components/data-table";
import { Button } from "@/components/ui/button";
import { Dialog,DialogContent,DialogDescription,DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { apiClient } from "@/lib/api";

const schema=z.object({code:z.string().min(1),name:z.string().min(1),phone:z.string(),email:z.string().email().or(z.literal("")),address:z.string(),notes:z.string()});type Form=z.infer<typeof schema>;
const defaults:Form={code:"",name:"",phone:"",email:"",address:"",notes:""};
export default function CustomersPage(){const client=useQueryClient();const [open,setOpen]=useState(false);const [editing,setEditing]=useState<TableRow|null>(null);const {register,handleSubmit,reset,formState:{errors}}=useForm<Form>({resolver:zodResolver(schema),defaultValues:defaults});const mutation=useMutation({mutationFn:(values:Form)=>apiClient(editing?`/customers/${editing.id}`:"/customers",{method:editing?"PUT":"POST",body:JSON.stringify(values)}),onSuccess:()=>{client.invalidateQueries({queryKey:["/customers"]});client.invalidateQueries({queryKey:["pos-customers"]});setOpen(false)}});function show(row?:TableRow){setEditing(row??null);reset(row?{code:String(row.code),name:String(row.name),phone:String(row.phone??""),email:String(row.email??""),address:String(row.address??""),notes:String(row.notes??"")}:defaults);setOpen(true)}async function remove(row:TableRow){if(!window.confirm(`Hapus pelanggan ${row.name}?`))return;await apiClient(`/customers/${row.id}`,{method:"DELETE"});client.invalidateQueries({queryKey:["/customers"]})}return <div className="space-y-6"><div><h1 className="text-3xl font-bold tracking-tight">Pelanggan</h1><p className="mt-2 text-muted-foreground">Master pelanggan untuk servis dan penjualan langsung.</p></div><DataTable endpoint="/customers" columns={[{key:"code",label:"Kode"},{key:"name",label:"Nama"},{key:"phone",label:"Telepon"},{key:"email",label:"Email"},{key:"address",label:"Alamat"}]} toolbar={<Button onClick={()=>show()}><Plus className="size-4"/>Tambah pelanggan</Button>} actions={row=><div className="flex gap-1"><Button variant="ghost" size="icon" onClick={()=>show(row)}><Pencil className="size-4"/></Button><Button variant="ghost" size="icon" onClick={()=>remove(row)}><Trash2 className="size-4 text-red-600"/></Button></div>}/><Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogTitle>{editing?"Edit pelanggan":"Tambah pelanggan"}</DialogTitle><DialogDescription>Data ini dapat dipilih kembali saat menerima motor.</DialogDescription><form className="mt-6 grid gap-4 sm:grid-cols-2" onSubmit={handleSubmit(values=>mutation.mutate(values))}>{(["code","name","phone","email","address","notes"] as const).map(name=><label key={name} className="text-sm font-medium capitalize">{name}<Input className="mt-2" {...register(name)}/>{errors[name]&&<span className="text-xs text-red-600">{errors[name]?.message}</span>}</label>)}{mutation.error&&<p className="text-sm text-red-600 sm:col-span-2">{mutation.error.message}</p>}<div className="flex justify-end gap-2 sm:col-span-2"><Button type="button" variant="outline" onClick={()=>setOpen(false)}>Batal</Button><Button>Simpan</Button></div></form></DialogContent></Dialog></div>}
