"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
import { Bike,Eye,Plus } from "lucide-react";
import Link from "next/link";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { DataTable,type TableRow } from "@/components/data-table";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog,DialogContent,DialogDescription,DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { apiClient } from "@/lib/api";
import { dateTime } from "@/lib/utils";

const schema=z.object({
 mode:z.enum(["new","existing"]),vehicle_id:z.string(),mechanic_id:z.string(),complaint:z.string().min(1,"Keluhan wajib diisi"),odometer:z.coerce.number().min(0),
 customer_name:z.string(),customer_phone:z.string(),customer_email:z.string(),customer_address:z.string(),
 identifier:z.string(),plate_number:z.string(),brand:z.string(),model:z.string(),year:z.coerce.number().min(0),color:z.string(),
}).superRefine((value,ctx)=>{if(value.mode==="existing"&&!value.vehicle_id)ctx.addIssue({code:"custom",path:["vehicle_id"],message:"Pilih kendaraan"});if(value.mode==="new"){if(!value.customer_name)ctx.addIssue({code:"custom",path:["customer_name"],message:"Nama pelanggan wajib diisi"});if(!value.identifier)ctx.addIssue({code:"custom",path:["identifier"],message:"Identitas motor wajib diisi"});if(value.customer_email&&!z.string().email().safeParse(value.customer_email).success)ctx.addIssue({code:"custom",path:["customer_email"],message:"Email tidak valid"})}});
type Form=z.infer<typeof schema>;type Vehicle={id:string;identifier:string;plate_number:string;brand:string;model:string};type Mechanic={id:string;name:string};
const defaults:Form={mode:"new",vehicle_id:"",mechanic_id:"",complaint:"",odometer:0,customer_name:"",customer_phone:"",customer_email:"",customer_address:"",identifier:"",plate_number:"",brand:"",model:"",year:0,color:""};
const statusLabel:Record<string,string>={inspection:"Pemeriksaan",approval:"Menunggu persetujuan",in_progress:"Dikerjakan",completed:"Selesai",invoiced:"Ditagihkan",cancelled:"Dibatalkan"};

export default function WorkOrdersPage(){
 const client=useQueryClient();const [open,setOpen]=useState(false);const vehicles=useQuery({queryKey:["intake-vehicles"],queryFn:()=>apiClient<Vehicle[]>("/vehicles?per_page=100&sort=created_at&direction=desc")});const mechanics=useQuery({queryKey:["mechanics"],queryFn:()=>apiClient<Mechanic[]>("/work-orders/options/mechanics")});
 const {register,watch,handleSubmit,reset,formState:{errors}}=useForm<Form>({resolver:zodResolver(schema),defaultValues:defaults});const mode=watch("mode");
 const mutation=useMutation({mutationFn:(values:Form)=>apiClient("/work-orders/intake",{method:"POST",body:JSON.stringify(values.mode==="existing"?{vehicle_id:values.vehicle_id,mechanic_id:values.mechanic_id||null,complaint:values.complaint,odometer:values.odometer}:{customer:{name:values.customer_name,phone:values.customer_phone,email:values.customer_email,address:values.customer_address},vehicle:{identifier:values.identifier,plate_number:values.plate_number,brand:values.brand,model:values.model,year:values.year,color:values.color},mechanic_id:values.mechanic_id||null,complaint:values.complaint,odometer:values.odometer})}),onSuccess:()=>{client.invalidateQueries({queryKey:["/work-orders"]});client.invalidateQueries({queryKey:["intake-vehicles"]});setOpen(false);reset(defaults)}});
 return <div className="space-y-6"><div><h1 className="text-3xl font-bold tracking-tight">Penerimaan & work order</h1><p className="mt-2 text-muted-foreground">Terima motor, tugaskan montir, catat barang dan jasa, lalu lanjutkan ke pembayaran.</p></div><DataTable endpoint="/work-orders" columns={[{key:"number",label:"Nomor"},{key:"vehicle_identifier",label:"Motor"},{key:"customer_name",label:"Pelanggan"},{key:"mechanic_name",label:"Montir"},{key:"status",label:"Status",format:value=><Badge className={value==="completed"||value==="invoiced"?"bg-emerald-100 text-emerald-700":value==="cancelled"?"bg-red-100 text-red-700":"bg-orange-100 text-orange-700"}>{statusLabel[String(value)]??String(value)}</Badge>},{key:"complaint",label:"Keluhan"},{key:"odometer",label:"Odometer"},{key:"created_at",label:"Diterima",format:value=>dateTime.format(new Date(String(value)))}]} toolbar={<Button onClick={()=>setOpen(true)}><Bike className="size-4"/>Terima motor</Button>} actions={(row:TableRow)=><Link href={`/dashboard/work-orders/${row.id}`} className="inline-flex h-9 items-center gap-2 rounded-lg border px-3 text-sm font-semibold hover:bg-muted"><Eye className="size-4"/>Buka</Link>}/>
 <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-w-3xl"><DialogTitle>Terima motor untuk servis</DialogTitle><DialogDescription>Gunakan kendaraan terdaftar atau catat pelanggan dan motor baru.</DialogDescription><form className="mt-6 space-y-5" onSubmit={handleSubmit(values=>mutation.mutate(values))}><div className="grid grid-cols-2 gap-2 rounded-xl bg-muted p-1"><button type="button" onClick={()=>reset({...defaults,mode:"new"})} className={`rounded-lg px-3 py-2 text-sm font-semibold ${mode==="new"?"bg-white shadow-sm":""}`}>Pelanggan baru</button><button type="button" onClick={()=>reset({...defaults,mode:"existing"})} className={`rounded-lg px-3 py-2 text-sm font-semibold ${mode==="existing"?"bg-white shadow-sm":""}`}>Motor terdaftar</button></div><input type="hidden" {...register("mode")}/>
 {mode==="existing"?<Field label="Kendaraan" error={errors.vehicle_id?.message}><select className="h-10 w-full rounded-xl border bg-white px-3 text-sm" {...register("vehicle_id")}><option value="">Pilih motor</option>{vehicles.data?.data?.map(vehicle=><option key={vehicle.id} value={vehicle.id}>{vehicle.identifier} · {vehicle.brand} {vehicle.model}</option>)}</select></Field>:<><div className="grid gap-4 sm:grid-cols-2"><Field label="Nama pelanggan" error={errors.customer_name?.message}><Input {...register("customer_name")}/></Field><Field label="Telepon"><Input {...register("customer_phone")}/></Field><Field label="Email" error={errors.customer_email?.message}><Input type="email" {...register("customer_email")}/></Field><Field label="Alamat"><Input {...register("customer_address")}/></Field></div><div className="border-t pt-5"><h3 className="mb-4 font-semibold">Identitas motor</h3><div className="grid gap-4 sm:grid-cols-3"><Field label="Identitas/plat" error={errors.identifier?.message}><Input placeholder="B 1234 XYZ" {...register("identifier")}/></Field><Field label="Plat nomor"><Input {...register("plate_number")}/></Field><Field label="Merek"><Input {...register("brand")}/></Field><Field label="Model"><Input {...register("model")}/></Field><Field label="Tahun"><Input type="number" {...register("year",{valueAsNumber:true})}/></Field><Field label="Warna"><Input {...register("color")}/></Field></div></div></>}
 <div className="grid gap-4 sm:grid-cols-2"><Field label="Montir"><select className="h-10 w-full rounded-xl border bg-white px-3 text-sm" {...register("mechanic_id")}><option value="">Belum ditugaskan</option>{mechanics.data?.data?.map(mechanic=><option key={mechanic.id} value={mechanic.id}>{mechanic.name}</option>)}</select></Field><Field label="Odometer"><Input type="number" {...register("odometer",{valueAsNumber:true})}/></Field></div><Field label="Keluhan pelanggan" error={errors.complaint?.message}><textarea className="min-h-24 w-full rounded-xl border p-3 text-sm" {...register("complaint")}/></Field>{mutation.error&&<p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{mutation.error.message}</p>}<div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={()=>setOpen(false)}>Batal</Button><Button disabled={mutation.isPending}><Plus className="size-4"/>{mutation.isPending?"Menyimpan...":"Buat work order"}</Button></div></form></DialogContent></Dialog></div>
}
function Field({label,error,children}:{label:string;error?:string;children:React.ReactNode}){return <label className="block text-sm font-medium">{label}<div className="mt-2">{children}</div>{error&&<span className="mt-1 block text-xs text-red-600">{error}</span>}</label>}
