"use client";
import { useQuery } from "@tanstack/react-query";
import { ArrowUpRight,Boxes,ClipboardList,WalletCards } from "lucide-react";
import Link from "next/link";
import { apiClient } from "@/lib/api";
import { rupiah } from "@/lib/utils";
import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card";
type Stats={monthly_revenue:number;open_work_orders:number;low_stock_products:number};
export default function Dashboard(){const {data}=useQuery({queryKey:["dashboard"],queryFn:()=>apiClient<Stats>("/dashboard")});const today=new Intl.DateTimeFormat("id-ID",{dateStyle:"full"}).format(new Date());const stats=[{label:"Omzet bulan ini",value:rupiah.format(data?.data?.monthly_revenue??0),icon:WalletCards,tone:"bg-emerald-50 text-emerald-700"},{label:"Work order aktif",value:String(data?.data?.open_work_orders??0),icon:ClipboardList,tone:"bg-orange-50 text-orange-700"},{label:"Stok perlu perhatian",value:String(data?.data?.low_stock_products??0),icon:Boxes,tone:"bg-blue-50 text-blue-700"}];return <div className="space-y-7"><div><p className="text-sm font-semibold capitalize text-primary">{today}</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Selamat datang, Owner.</h1><p className="mt-2 text-muted-foreground">Berikut kondisi bengkel hari ini.</p></div><div className="grid gap-4 md:grid-cols-3">{stats.map(item=><Card key={item.label}><CardContent className="flex items-start justify-between p-6"><div><p className="text-sm text-muted-foreground">{item.label}</p><p className="mt-3 text-2xl font-bold">{item.value}</p></div><span className={`grid size-11 place-items-center rounded-xl ${item.tone}`}><item.icon className="size-5"/></span></CardContent></Card>)}</div><div className="grid gap-5 lg:grid-cols-[1.4fr_.6fr]"><Card><CardHeader><CardTitle>Alur kerja hari ini</CardTitle></CardHeader><CardContent><div className="grid grid-cols-4 gap-3">{[["Antrean","3"],["Inspeksi","2"],["Dikerjakan","4"],["Selesai","7"]].map(([label,value])=><div key={label} className="rounded-xl bg-muted p-4"><p className="text-2xl font-bold">{value}</p><p className="mt-1 text-xs text-muted-foreground">{label}</p></div>)}</div><Link href="/dashboard/work-orders" className="mt-5 flex items-center gap-2 text-sm font-semibold text-primary">Lihat semua work order <ArrowUpRight className="size-4"/></Link></CardContent></Card><Card><CardHeader><CardTitle>Aksi cepat</CardTitle></CardHeader><CardContent className="space-y-2"><Link href="/dashboard/pos" className="block rounded-xl bg-primary p-4 font-semibold text-white">Buat transaksi baru</Link><Link href="/dashboard/work-orders" className="block rounded-xl border p-4 font-semibold">Terima kendaraan</Link><Link href="/dashboard/inventory" className="block rounded-xl border p-4 font-semibold">Penyesuaian stok</Link></CardContent></Card></div></div>}
